a=[6,1,2,3,3,4,5]
print(a)
reverse = a.reverse()
print(reverse)
print(a)
sort = a.sort(reverse=True)
print(a)
print(sort)
l = sorted(a)
print(a)
print(l)
insert = a.insert(0, 888888)
print(a)
print(insert)
#
# append = a.append(['kk','kkl'])
# print(a)
# print(append)
# extend = a.extend(['a', 'b'])
# print(extend)
# print(a)
# a.insert(0,'good')
# print(a)
# a.remove(3)
# print(a)
# pop = a.pop()
# print(pop)
# print(a)
# remove = a.remove(2)
# print(remove)
# print(a)
# pop = a.pop()
# print(pop)
# print(a)
# del a[1]
# print(a)